/** Texto largo de la página Quién soy (párrafos en orden). */
export const quienSoyParagraphs: string[] = [
  "Siempre tuve afinidad por lo digital: habiendo crecido en un mundo ya colmado por eso, forma parte de mí desde que soy muy pequeño. Recuerdo tardes enteras descubriendo YouTube con 8 o 9 años, escuchando música con videos y ese tipo de cosas.",
  "También me la pasaba dibujando; esta combinación me llevó a interesarme mucho por comunicar algo. Posteriormente y desde joven, empecé a trabajar con familiares en distintos proyectos: por ejemplo, cuando tenía 13 años ayudaba en la producción y el contenido de lo que en ese momento eran jugos naturales prensados en frío, que luego se volvió una tienda saludable integral. También hacía el contenido en redes de una tienda de plantines y semillas orgánicas de frutales y verduras. Recuerdo que mi madrastra me pasaba los textos y yo los mejoraba y me encargaba de subir todo a Instagram, armar los posts con las fotos y demás. Parecen cosas insignificantes, pero en realidad ya estaba armando un camino que, sin darme cuenta, me llevaba a ciertos lugares.",
  "Posteriormente, en 2023, ya con 19 años y estudiando música, empecé a estudiar ventas, creación de productos, lanzamientos y venta evergreen, conectando con emprendedores e infoproductores que quieren vender más y escalar su negocio. Esto inició con ATV, la academia en la que participaba y en la que aprendí muchísimo, y conocí a algunas personas de otros países; era muy emocionante hablar con otras personas jóvenes que estaban persiguiendo lo mismo que uno. Recuerdo que mi primera llamada para realizar un acuerdo de una propuesta fue con una persona que tiene una cuenta con más de 2 millones de seguidores. Yo estaba tan nervioso como nunca en mi vida y, obviamente, no logré lo que esperaba, pero sí aprendí muchísimo. A los meses de eso, estaba viajando solo a Buenos Aires a concretar un acuerdo con Juan Pablo Francolini (investigador en ciencia y mitología), con el cual trabajé varios meses, tanto en contenido como en ventas. Eso fue muy emocionante para mí, ya que viajar solo a hacer negocios con 20 años era todo un borde. En ese transcurso de tiempo también preparé en ventas y estrategias al equipo de Maxi Sánchez (bioconstrucción y permacultura).",
  "En el transcurso del tiempo he colaborado con más creadores. Uno de los más importantes es Cresciente, teoría musical: una academia online de música con alumnos en todo el mundo. En este proyecto se combinaron dos mundos, lo digital y la música, ya que trabajaba con WordPress (que aprendí a usar en este trabajo) y también tenía que leer partituras y procesar audio en Reaper. Específicamente me contrataron para hacer una actualización inmensa en el sitio: actualizar los ciclos de estudio de la academia, es decir, actualizar cientos de clases en menos de un año. La experiencia fue genial y, de hecho, en el transcurso nos volvimos grandes amigos con los creadores de Cresciente <3. Aprendí qué es la gestión y organización de lo que es literalmente una empresa, y la verdadera ganancia para mí en eso fue integrar en mi vida la organización y continuidad que tiene Cresciente.",
  "Actualmente estoy trabajando más en desarrollo de software, creando proyectos propios que son negocios también y trabajando con clientes. Al mismo tiempo me dedico a mi música, desarrollando mi primer disco solista e indagando en la música para audiovisuales, y además iniciando un negocio de creación de dispositivos de audio junto a mi pareja. Por todas estas cosas es que elijo que la primera palabra de mi portfolio sea Creador.",
]

export const quienSoyUpdateTitle = "Actualizacion 09/2026"

export const quienSoyUpdateParagraphs: string[] = [
  "En 2026 me di cuenta que colaborar con artistas daba ciertas posibilidades creativas que otros sectores no, y empecé a hablar con algunos artistas, después de los primeros trabajos, me di cuenta de que, más allá de las posibilidades creativas... centrarme en generar espacios para promover el arte es lo más importante, ahí me conecté más conmigo como artista y me di cuenta de lo importante que es lo que puedo hacer.",
  "En este proceso, mi novia empezó a acompañarme, primero viendo algunas webs, probando, recomendando cosas, luego posteriormente se unió al proyecto, formamos un equipo de trabajo y juntos estamos creando nuevos sistemas y métodos para crear espacios de arte.",
]
